name: Fetch Upstream

on:
  schedule:
    - cron: '7 0 * * *'
  # Allows manual workflow run (must in default branch to work)
  workflow_dispatch:

jobs:
  fetch:
    uses: weewx-extensions/development-tools/.github/workflows/fetch.yml@latest
    with:
      upstream_url: "https://github.com/weewx-mqtt/publish.git"
